using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using SunEyeVision.Plugin.Infrastructure;
using SunEyeVision.Plugin.Abstractions;
using SunEyeVision.UI.Diagnostics;
using SunEyeVision.UI.Factories;

namespace SunEyeVision.UI.Views.Windows
{
    /// <summary>
    /// DebugWindow.xaml 的交互逻辑 - 支持自定义控件和自动生成控件的混合模式
    /// </summary>
    public partial class DebugWindow : Window, INotifyPropertyChanged, IDebugControlProvider
    {
        public event PropertyChangedEventHandler? PropertyChanged;

        private string _toolName = "";
        private string _toolType = "";
        private string _toolStatus = "就绪";
        private string _statusMessage = "等待执行...";
        private string _executionTime = "0 ms";
        private string _fps = "0.0";
        private IToolPlugin? _toolPlugin;
        private ToolMetadata? _toolMetadata;
        private bool _useCustomControl = false;

        public string ToolName
        {
            get => _toolName;
            set
            {
                if (_toolName != value)
                {
                    _toolName = value;
                    PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(ToolName)));
                }
            }
        }

        public string ToolType
        {
            get => _toolType;
            set
            {
                if (_toolType != value)
                {
                    _toolType = value;
                    PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(ToolType)));
                }
            }
        }

        public string ToolStatus
        {
            get => _toolStatus;
            set
            {
                if (_toolStatus != value)
                {
                    _toolStatus = value;
                    PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(ToolStatus)));
                }
            }
        }

        public string StatusMessage
        {
            get => _statusMessage;
            set
            {
                if (_statusMessage != value)
                {
                    _statusMessage = value;
                    PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(StatusMessage)));
                }
            }
        }

        public string ExecutionTime
        {
            get => _executionTime;
            set
            {
                if (_executionTime != value)
                {
                    _executionTime = value;
                    PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(ExecutionTime)));
                }
            }
        }

        public string FPS
        {
            get => _fps;
            set
            {
                if (_fps != value)
                {
                    _fps = value;
                    PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(FPS)));
                }
            }
        }

        public ObservableCollection<ToolParameter> ToolParameters { get; }

        public DebugWindow(string toolId, IToolPlugin toolPlugin, ToolMetadata toolMetadata)
        {
            InitializeComponent();
            DataContext = this;

            _toolPlugin = toolPlugin;
            _toolMetadata = toolMetadata;
            ToolName = toolMetadata.DisplayName;
            ToolType = toolId;

            ToolParameters = new ObservableCollection<ToolParameter>();
            
            InitializeDebugInterface();
        }

        /// <summary>
        /// 初始化调试界面 - 根据工具配置决定使用自定义控件还是自动生成控件
        /// </summary>
        private void InitializeDebugInterface()
        {
            var customControlContainer = this.FindName("customControlContainer") as System.Windows.Controls.Panel;

            if (customControlContainer != null)
            {
                // 检查工具是否提供自定义控件
                if (_toolPlugin is IDebugControlProvider debugProvider &&
                    debugProvider.HasCustomDebugControl(ToolType))
                {
                    var customControl = debugProvider.CreateDebugControl(ToolType);
                    if (customControl != null)
                    {
                        _useCustomControl = true;
                        customControlContainer.Children.Add(customControl);
                        StatusMessage = "使用自定义调试控件";
                        return;
                    }
                }

                // 使用自动生成的控件
                LoadAutoGeneratedControls(customControlContainer);
            }
            else
            {
                // 向后兼容模式 - 保留原有的硬编码参数加载
                LoadDefaultParameters(ToolType);
            }
        }

        /// <summary>
        /// 加载自动生成的参数控件
        /// </summary>
        private void LoadAutoGeneratedControls(System.Windows.Controls.Panel container)
        {
            if (_toolMetadata?.InputParameters == null || _toolMetadata.InputParameters.Count == 0)
            {
                StatusMessage = "工具没有配置参数";
                return;
            }

            // 按分组组织参数
            var parameterGroups = new Dictionary<string, List<ParameterMetadata>>();
            foreach (var param in _toolMetadata.InputParameters)
            {
                var category = string.IsNullOrEmpty(param.Category) ? "基本参数" : param.Category;
                if (!parameterGroups.ContainsKey(category))
                {
                    parameterGroups[category] = new List<ParameterMetadata>();
                }
                parameterGroups[category].Add(param);
            }

            // 为每个分组创建UI
            foreach (var group in parameterGroups)
            {
                var groupBorder = CreateParameterGroupBorder(group.Key);
                var stackPanel = groupBorder.Child as StackPanel;

                if (stackPanel != null)
                {
                    foreach (var param in group.Value)
                    {
                        var paramControl = CreateParameterControl(param);
                        stackPanel.Children.Add(paramControl);
                    }
                }

                container.Children.Add(groupBorder);
            }

            StatusMessage = $"加载了 {_toolMetadata.InputParameters.Count} 个参数";
        }

        /// <summary>
        /// 创建参数分组边框
        /// </summary>
        private Border CreateParameterGroupBorder(string groupName)
        {
            var border = new Border
            {
                Background = new SolidColorBrush(Color.FromRgb(255, 255, 255)),
                BorderBrush = new SolidColorBrush(Color.FromRgb(224, 224, 224)),
                BorderThickness = new Thickness(1),
                CornerRadius = new CornerRadius(4),
                Margin = new Thickness(0, 0, 0, 8)
            };

            var stackPanel = new StackPanel();

            // 分组标题
            var headerBorder = new Border
            {
                Background = new SolidColorBrush(System.Windows.Media.Color.FromRgb(240, 248, 255)),
                Padding = new Thickness(8),
                BorderBrush = new SolidColorBrush(System.Windows.Media.Color.FromRgb(0, 102, 204)),
                BorderThickness = new Thickness(0, 0, 0, 2)
            };

            var headerText = new TextBlock
            {
                Text = $"📂 {groupName}",
                FontWeight = FontWeights.Bold,
                FontSize = 12,
                Foreground = new SolidColorBrush(Color.FromRgb(0, 102, 204))
            };

            headerBorder.Child = headerText;
            stackPanel.Children.Add(headerBorder);

            border.Child = stackPanel;
            return border;
        }

        /// <summary>
        /// 创建单个参数控件
        /// </summary>
        private FrameworkElement CreateParameterControl(ParameterMetadata param)
        {
            var border = new Border
            {
                Padding = new Thickness(8),
                BorderBrush = new SolidColorBrush(Color.FromRgb(240, 240, 240)),
                BorderThickness = new Thickness(0, 0, 0, 1)
            };

            var grid = new Grid();
            grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(80) });
            grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) });

            // 参数名称
            var nameText = new TextBlock
            {
                Text = param.DisplayName,
                VerticalAlignment = VerticalAlignment.Center,
                FontSize = 11,
                Foreground = new SolidColorBrush(Color.FromRgb(102, 102, 102))
            };

            if (param.Required)
            {
                nameText.Text += " *";
                nameText.FontWeight = FontWeights.SemiBold;
            }

            Grid.SetColumn(nameText, 0);
            grid.Children.Add(nameText);

            // 参数控件
            var control = ParameterControlFactory.CreateControl(param);
            Grid.SetColumn(control, 1);
            grid.Children.Add(control);

            // 参数描述（如果有）
            if (!string.IsNullOrEmpty(param.Description))
            {
                var descText = new TextBlock
                {
                    Text = param.Description,
                    FontSize = 10,
                    Foreground = new SolidColorBrush(Color.FromRgb(153, 153, 153)),
                    TextWrapping = TextWrapping.Wrap,
                    Margin = new Thickness(80, 2, 0, 0)
                };
                grid.RowDefinitions.Add(new RowDefinition { Height = GridLength.Auto });
                grid.RowDefinitions.Add(new RowDefinition { Height = GridLength.Auto });
                Grid.SetRow(nameText, 0);
                Grid.SetRow(control, 0);
                Grid.SetRow(descText, 1);
                Grid.SetColumn(descText, 0);
                Grid.SetColumnSpan(descText, 2);
                grid.Children.Add(descText);
            }

            border.Child = grid;
            return border;
        }

        /// <summary>
        /// IDebugControlProvider 实现
        /// </summary>
        public object GetDebugPanel()
        {
            return this;
        }

        public void StartDebug()
        {
            // 开始调试逻辑
        }

        public void StopDebug()
        {
            // 停止调试逻辑
        }

        public void Step()
        {
            // 单步执行逻辑
        }

        public void Reset()
        {
            // 重置调试逻辑
        }

        public bool HasCustomDebugControl(string toolType)
        {
            // 检查是否有自定义调试控件
            return _toolPlugin is IDebugControlProvider;
        }

        public FrameworkElement CreateDebugControl(string toolType)
        {
            // 创建自定义调试控件
            if (_toolPlugin is IDebugControlProvider debugProvider)
            {
                return debugProvider.CreateDebugControl(toolType);
            }
            return null;
        }

        private void LoadDefaultParameters(string toolType)
        {
            ToolParameters.Clear();

            switch (toolType)
            {
                case "GaussianBlur":
                    ToolParameters.Add(new ToolParameter { Name = "KernelSize", Value = "5" });
                    ToolParameters.Add(new ToolParameter { Name = "Sigma", Value = "1.0" });
                    break;
                case "Threshold":
                    ToolParameters.Add(new ToolParameter { Name = "Threshold", Value = "128" });
                    ToolParameters.Add(new ToolParameter { Name = "Invert", Value = "False" });
                    break;
                case "GrayScale":
                    ToolParameters.Add(new ToolParameter { Name = "Method", Value = "Average" });
                    break;
                case "EdgeDetection":
                    ToolParameters.Add(new ToolParameter { Name = "Method", Value = "Canny" });
                    ToolParameters.Add(new ToolParameter { Name = "Threshold1", Value = "50" });
                    ToolParameters.Add(new ToolParameter { Name = "Threshold2", Value = "150" });
                    break;
                case "ImageCapture":
                    ToolParameters.Add(new ToolParameter { Name = "Camera", Value = "相机1" });
                    ToolParameters.Add(new ToolParameter { Name = "Exposure", Value = "10000" });
                    ToolParameters.Add(new ToolParameter { Name = "Gain", Value = "10.5" });
                    break;
                case "TemplateMatching":
                    ToolParameters.Add(new ToolParameter { Name = "Template", Value = "template.png" });
                    ToolParameters.Add(new ToolParameter { Name = "Threshold", Value = "0.8" });
                    ToolParameters.Add(new ToolParameter { Name = "Method", Value = "Normalized Correlation" });
                    break;
                default:
                    ToolParameters.Add(new ToolParameter { Name = "Parameter1", Value = "" });
                    break;
            }
        }

        /// <summary>
        /// 获取当前参数值
        /// </summary>
        public Dictionary<string, object> GetParameterValues()
        {
            var values = new Dictionary<string, object>();

            if (_useCustomControl)
            {
                // 自定义控件模式 - 需要调用者从自定义控件获取值
                return values;
            }

            // 自动生成控件模式
            if (_toolMetadata?.InputParameters != null)
            {
                var container = this.FindName("customControlContainer") as System.Windows.Controls.Panel;
                if (container != null)
                {
                    foreach (var param in _toolMetadata.InputParameters)
                    {
                        var value = ExtractValueFromContainer(container, param);
                        if (value != null)
                        {
                            values[param.Name] = value;
                        }
                    }
                }
            }

            return values;
        }

        /// <summary>
        /// 从容器中提取参数值
        /// </summary>
        private object? ExtractValueFromContainer(System.Windows.Controls.Panel container, ParameterMetadata param)
        {
            foreach (var child in container.Children)
            {
                if (child is Border border && border.Child is StackPanel stackPanel)
                {
                    foreach (var spChild in stackPanel.Children)
                    {
                        if (spChild is Grid grid)
                        {
                            var control = FindParameterControl(grid);
                            if (control != null)
                            {
                                return ConvertControlValue(control, param);
                            }
                        }
                    }
                }
            }
            return param.DefaultValue;
        }

        /// <summary>
        /// 在Grid中查找参数控件
        /// </summary>
        private Control? FindParameterControl(Grid grid)
        {
            foreach (var child in grid.Children)
            {
                if (child is Control control && !(child is TextBlock))
                {
                    return control;
                }
            }
            return null;
        }

        /// <summary>
        /// 转换控件值为参数类型
        /// </summary>
        private object? ConvertControlValue(Control control, ParameterMetadata param)
        {
            try
            {
                switch (param.Type)
                {
                    case ParameterType.Int:
                        if (control is TextBox textBox)
                        {
                            return int.TryParse(textBox.Text, out var intVal) ? intVal : (int?)null;
                        }
                        break;

                    case ParameterType.Double:
                        if (control is TextBox textBoxDbl)
                        {
                            return double.TryParse(textBoxDbl.Text, out var dblVal) ? dblVal : (double?)null;
                        }
                        break;

                    case ParameterType.Bool:
                        if (control is CheckBox checkBox)
                        {
                            return checkBox.IsChecked;
                        }
                        break;

                    case ParameterType.Enum:
                        if (control is ComboBox comboBox)
                        {
                            return comboBox.SelectedItem?.ToString();
                        }
                        break;

                    case ParameterType.String:
                        if (control is TextBox textBoxStr)
                        {
                            return textBoxStr.Text;
                        }
                        break;

                    default:
                        return null;
                }
            }
            catch
            {
                return param.DefaultValue;
            }

            return param.DefaultValue;
        }

        #region 图像显示

        private void btnOriginal_Click(object sender, RoutedEventArgs e)
        {
            SetActiveButton(sender as Button);
            ShowPlaceholder("原图");
        }

        private void btnProcessed_Click(object sender, RoutedEventArgs e)
        {
            SetActiveButton(sender as Button);
            ShowPlaceholder("处理后");
        }

        private void btnResult_Click(object sender, RoutedEventArgs e)
        {
            SetActiveButton(sender as Button);
            ShowPlaceholder("检测结果");
        }

        private void SetActiveButton(Button? activeButton)
        {
            if (activeButton == null) return;

            btnOriginal.Background = activeButton == btnOriginal ? new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(255, 255, 255)) : new System.Windows.Media.SolidColorBrush(System.Windows.Media.Colors.Transparent);
            btnProcessed.Background = activeButton == btnProcessed ? new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(255, 255, 255)) : new System.Windows.Media.SolidColorBrush(System.Windows.Media.Colors.Transparent);
            btnResult.Background = activeButton == btnResult ? new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(255, 255, 255)) : new System.Windows.Media.SolidColorBrush(System.Windows.Media.Colors.Transparent);
        }

        private void ShowPlaceholder(string text)
        {
            imgDisplay.Source = null;
            txtNoImage.Text = $"暂无{text}";
            txtNoImage.Visibility = Visibility.Visible;
        }

        private void btnZoomIn_Click(object sender, RoutedEventArgs e)
        {
            StatusMessage = "放大图像";
        }

        private void btnZoomOut_Click(object sender, RoutedEventArgs e)
        {
            StatusMessage = "缩小图像";
        }

        private void btnFit_Click(object sender, RoutedEventArgs e)
        {
            StatusMessage = "适应窗口";
        }

        private void btn1to1_Click(object sender, RoutedEventArgs e)
        {
            StatusMessage = "1:1 显示";
        }

        #endregion

        #region 执行控制

        private void btnRun_Click(object sender, RoutedEventArgs e)
        {
            ToolStatus = "运行中";
            StatusMessage = "正在执行工具...";

            var random = new Random();
            ExecutionTime = $"{random.Next(5, 50)} ms";
            FPS = $"{random.Next(20, 60)}.{random.Next(0, 9)}";

            StatusMessage = "执行完成";
            ToolStatus = "就绪";
        }

        private void btnReset_Click(object sender, RoutedEventArgs e)
        {
            if (_useCustomControl)
            {
                StatusMessage = "自定义控件模式，请重置自定义控件";
            }
            else
            {
                LoadDefaultParameters(ToolType);
                StatusMessage = "参数已重置";
            }
            ToolStatus = "就绪";
        }

        #endregion
    }

    /// <summary>
    /// 工具参数模型
    /// </summary>
    public class ToolParameter : INotifyPropertyChanged
    {
        private string _name = "";
        private string _value = "";

        public event PropertyChangedEventHandler? PropertyChanged;

        public string Name
        {
            get => _name;
            set
            {
                if (_name != value)
                {
                    _name = value;
                    PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Name)));
                }
            }
        }

        public string Value
        {
            get => _value;
            set
            {
                if (_value != value)
                {
                    _value = value;
                    PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Value)));
                }
            }
        }
    }
}
